import { MarbleSkin } from '../types';

export const SKINS: MarbleSkin[] = [
  {
    id: 'chrome',
    name: 'Chrome',
    color: '#e8e8e8',
    metalness: 0.95,
    roughness: 0.05,
    emissive: '#000000',
    emissiveIntensity: 0,
    cost: 0,
  },
  {
    id: 'gold',
    name: 'Gold',
    color: '#ffd700',
    metalness: 1.0,
    roughness: 0.1,
    emissive: '#332200',
    emissiveIntensity: 0.2,
    cost: 100,
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    color: '#1a1a2e',
    metalness: 0.8,
    roughness: 0.2,
    emissive: '#6600ff',
    emissiveIntensity: 0.15,
    cost: 150,
  },
  {
    id: 'plasma',
    name: 'Plasma',
    color: '#ff00ff',
    metalness: 0.6,
    roughness: 0.1,
    emissive: '#ff00ff',
    emissiveIntensity: 0.4,
    cost: 200,
  },
  {
    id: 'ice',
    name: 'Ice',
    color: '#aaddff',
    metalness: 0.3,
    roughness: 0.05,
    emissive: '#0055ff',
    emissiveIntensity: 0.1,
    cost: 120,
  },
  {
    id: 'lava',
    name: 'Lava',
    color: '#ff3300',
    metalness: 0.4,
    roughness: 0.3,
    emissive: '#ff6600',
    emissiveIntensity: 0.5,
    cost: 180,
  },
  {
    id: 'emerald',
    name: 'Emerald',
    color: '#00cc66',
    metalness: 0.7,
    roughness: 0.15,
    emissive: '#003322',
    emissiveIntensity: 0.1,
    cost: 160,
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    color: '#6633cc',
    metalness: 0.9,
    roughness: 0.05,
    emissive: '#220066',
    emissiveIntensity: 0.3,
    cost: 250,
    unlockStars: 100,
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    color: '#ffffff',
    metalness: 0.5,
    roughness: 0.1,
    emissive: '#ff88cc',
    emissiveIntensity: 0.3,
    cost: 300,
    unlockStars: 130,
  },
];

export const DEFAULT_SKIN = 'chrome';
