import { World } from '../types';

export const WORLDS: World[] = [
  {
    id: 1,
    name: 'Crystal Caves',
    subtitle: 'World 1',
    description: 'Shimmering underground caverns of ice-blue crystal.',
    starsToUnlock: 0,
    musicTrack: 'crystal',
    mazeWidth: 5,
    mazeHeight: 4,
    holeChance: 0.0,
    obstacleCount: 0,
    couponCategory: 'fashion',
    theme: {
      wallColor: '#3a5f8a',
      floorColor: '#1e3a5f',
      accentColor: '#7ec8e3',
      ambientColor: '#aaddff',
      fogColor: '#0a1a2a',
      skyColor: '#05101a',
      dirLightColor: '#c0e8ff',
      dirLightIntensity: 1.2,
      ambientIntensity: 0.5,
      marbleRestitution: 0.25,
      marbleFriction: 0.4,
      gravityScale: 1.0,
    },
  },
  {
    id: 2,
    name: 'Lava Lands',
    subtitle: 'World 2',
    description: 'Scorching volcanic plains — one wrong step and you\'re toast.',
    starsToUnlock: 8,
    musicTrack: 'lava',
    mazeWidth: 6,
    mazeHeight: 5,
    holeChance: 0.06,
    obstacleCount: 1,
    couponCategory: 'sports',
    theme: {
      wallColor: '#6b2800',
      floorColor: '#3d1500',
      accentColor: '#ff6a00',
      ambientColor: '#ff4400',
      fogColor: '#1a0800',
      skyColor: '#100400',
      dirLightColor: '#ffaa44',
      dirLightIntensity: 1.4,
      ambientIntensity: 0.6,
      marbleRestitution: 0.15,
      marbleFriction: 0.5,
      gravityScale: 1.1,
    },
  },
  {
    id: 3,
    name: 'Forest Floor',
    subtitle: 'World 3',
    description: 'Ancient mossy ruins winding through a dense woodland.',
    starsToUnlock: 20,
    musicTrack: 'forest',
    mazeWidth: 6,
    mazeHeight: 5,
    holeChance: 0.04,
    obstacleCount: 2,
    couponCategory: 'food_drink',
    theme: {
      wallColor: '#2d5a1b',
      floorColor: '#1a3310',
      accentColor: '#88cc44',
      ambientColor: '#66aa33',
      fogColor: '#0a1a05',
      skyColor: '#050e03',
      dirLightColor: '#ccffaa',
      dirLightIntensity: 1.0,
      ambientIntensity: 0.45,
      marbleRestitution: 0.2,
      marbleFriction: 0.6,
      gravityScale: 1.0,
    },
  },
  {
    id: 4,
    name: 'Space Station',
    subtitle: 'World 4',
    description: 'Derelict zero-gravity platforms drifting through the cosmos.',
    starsToUnlock: 36,
    musicTrack: 'space',
    mazeWidth: 7,
    mazeHeight: 5,
    holeChance: 0.08,
    obstacleCount: 2,
    couponCategory: 'electronics',
    theme: {
      wallColor: '#1a1a3a',
      floorColor: '#0d0d20',
      accentColor: '#00ccff',
      ambientColor: '#334466',
      fogColor: '#020208',
      skyColor: '#010105',
      dirLightColor: '#88aaff',
      dirLightIntensity: 1.1,
      ambientIntensity: 0.35,
      marbleRestitution: 0.35,
      marbleFriction: 0.2,
      gravityScale: 0.8,
    },
  },
  {
    id: 5,
    name: 'Ocean Depths',
    subtitle: 'World 5',
    description: 'Sunken temples beneath miles of crushing deep-sea pressure.',
    starsToUnlock: 56,
    musicTrack: 'ocean',
    mazeWidth: 7,
    mazeHeight: 6,
    holeChance: 0.1,
    obstacleCount: 3,
    couponCategory: 'travel',
    theme: {
      wallColor: '#003366',
      floorColor: '#001a3a',
      accentColor: '#00ffcc',
      ambientColor: '#006699',
      fogColor: '#000d1a',
      skyColor: '#000810',
      dirLightColor: '#44aaff',
      dirLightIntensity: 0.9,
      ambientIntensity: 0.4,
      marbleRestitution: 0.2,
      marbleFriction: 0.55,
      gravityScale: 1.15,
    },
  },
  {
    id: 6,
    name: 'Sky Kingdom',
    subtitle: 'World 6',
    description: 'Impossible floating citadels balanced among the clouds.',
    starsToUnlock: 80,
    musicTrack: 'sky',
    mazeWidth: 8,
    mazeHeight: 6,
    holeChance: 0.12,
    obstacleCount: 4,
    couponCategory: 'home_garden',
    theme: {
      wallColor: '#d4af37',
      floorColor: '#8b6914',
      accentColor: '#fffacd',
      ambientColor: '#ffeedd',
      fogColor: '#cce0ff',
      skyColor: '#aaccff',
      dirLightColor: '#ffffff',
      dirLightIntensity: 1.5,
      ambientIntensity: 0.7,
      marbleRestitution: 0.3,
      marbleFriction: 0.3,
      gravityScale: 1.2,
    },
  },
];

export const TOTAL_WORLDS = WORLDS.length;
export const LEVELS_PER_WORLD = 8;
export const TOTAL_LEVELS = TOTAL_WORLDS * LEVELS_PER_WORLD;
export const MAX_STARS_PER_LEVEL = 3;
export const MAX_TOTAL_STARS = TOTAL_LEVELS * MAX_STARS_PER_LEVEL;
